/*
 * Mayfair Stock Control.
 *
 */
package main.java;

import java.awt.Color;
import static java.awt.Color.white;
import java.awt.EventQueue;
import static java.awt.Frame.MAXIMIZED_BOTH;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import main.java.MayfairStatic.DesktopPanePainter;
import main.java.product.Products;
import main.java.customer.Customers;
import main.java.order.purchase.CurrentPurchaseOrders;
import main.java.order.purchase.NewPurchaseOrderStep1;
import main.java.order.purchase.PastPurchaseOrders;
import main.java.order.sales.CurrentSalesOrders;
import main.java.order.sales.NewSalesOrderStep1;
import main.java.order.sales.PastSalesOrders;
import main.java.reminders.Reminders;
import main.java.report.Reports;

/**
 *
 * @author kian_bryen
 */
public class App extends JFrame
{

    public App()
    {
        initComponents();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        try
        {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
            UIManager.getLookAndFeelDefaults().put("DesktopPane[Enabled].backgroundPainter",
                    new DesktopPanePainter());
            UIManager.put("control", white);
        }
        catch (UnsupportedLookAndFeelException ex)
        {
            MayfairStatic.outputMessage(null, ex);
        }

        /* Create and display the form */
        EventQueue.invokeLater(() ->
        {
            App jFrame = new App();
            jFrame.setVisible(true);
            jFrame.setExtendedState(MAXIMIZED_BOTH);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelSelection = new javax.swing.JPanel();
        btnNewSO = new javax.swing.JButton();
        btnCurrentSO = new javax.swing.JButton();
        btnNewPO = new javax.swing.JButton();
        btnCurrentPO = new javax.swing.JButton();
        btnProducts = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        btnCustomers = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        btnPastSO = new javax.swing.JButton();
        btnPastPO = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        btnReminders = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JSeparator();
        desktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MTC Stock Control System");

        panelSelection.setBackground(new java.awt.Color(255, 255, 255));
        panelSelection.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnNewSO.setBackground(new java.awt.Color(255, 255, 255));
        btnNewSO.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        btnNewSO.setText("New Order");
        btnNewSO.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNewSOActionPerformed(evt);
            }
        });

        btnCurrentSO.setBackground(new java.awt.Color(255, 255, 255));
        btnCurrentSO.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        btnCurrentSO.setText("Current");
        btnCurrentSO.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCurrentSOActionPerformed(evt);
            }
        });

        btnNewPO.setBackground(new java.awt.Color(255, 255, 255));
        btnNewPO.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        btnNewPO.setText("New Order");
        btnNewPO.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNewPOActionPerformed(evt);
            }
        });

        btnCurrentPO.setBackground(new java.awt.Color(255, 255, 255));
        btnCurrentPO.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        btnCurrentPO.setText("Current");
        btnCurrentPO.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCurrentPOActionPerformed(evt);
            }
        });

        btnProducts.setBackground(new java.awt.Color(255, 255, 255));
        btnProducts.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        btnProducts.setText("Products");
        btnProducts.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnProductsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sales Orders");

        btnCustomers.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomers.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        btnCustomers.setText("Customers");
        btnCustomers.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCustomersActionPerformed(evt);
            }
        });

        btnPastSO.setBackground(new java.awt.Color(255, 255, 255));
        btnPastSO.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        btnPastSO.setText("Past");
        btnPastSO.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPastSOActionPerformed(evt);
            }
        });

        btnPastPO.setBackground(new java.awt.Color(255, 255, 255));
        btnPastPO.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        btnPastPO.setText("Past");
        btnPastPO.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPastPOActionPerformed(evt);
            }
        });

        btnReports.setBackground(new java.awt.Color(255, 255, 255));
        btnReports.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        btnReports.setText("Reports");
        btnReports.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnReportsActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Purchase Orders");

        btnReminders.setBackground(new java.awt.Color(255, 255, 255));
        btnReminders.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        btnReminders.setText("Reminders");
        btnReminders.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnRemindersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSelectionLayout = new javax.swing.GroupLayout(panelSelection);
        panelSelection.setLayout(panelSelectionLayout);
        panelSelectionLayout.setHorizontalGroup(
            panelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelectionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNewSO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCurrentSO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPastSO, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addComponent(btnProducts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator8)
                    .addComponent(jSeparator9)
                    .addComponent(btnCustomers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator10)
                    .addComponent(btnPastPO, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnNewPO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCurrentPO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator11)
                    .addComponent(jSeparator12)
                    .addComponent(btnReminders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelSelectionLayout.setVerticalGroup(
            panelSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSelectionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewSO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCurrentSO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPastSO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNewPO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCurrentPO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPastPO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProducts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCustomers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReminders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        getContentPane().add(panelSelection, java.awt.BorderLayout.LINE_START);

        desktop.setBackground(new java.awt.Color(255, 255, 255));
        desktop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );

        getContentPane().add(desktop, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewSOActionPerformed
        NewSalesOrderStep1 jFrame = new NewSalesOrderStep1(desktop);
        desktop.add(jFrame);
        jFrame.show();
    }//GEN-LAST:event_btnNewSOActionPerformed

    private void btnCurrentSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentSOActionPerformed
        CurrentSalesOrders jFrame = new CurrentSalesOrders(desktop);
        desktop.add(jFrame);
        MayfairStatic.setMaximum(jFrame);
        jFrame.show();
    }//GEN-LAST:event_btnCurrentSOActionPerformed

    private void btnNewPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPOActionPerformed
        NewPurchaseOrderStep1 jFrame = new NewPurchaseOrderStep1(desktop);
        desktop.add(jFrame);
        jFrame.show();
    }//GEN-LAST:event_btnNewPOActionPerformed

    private void btnCurrentPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCurrentPOActionPerformed
        CurrentPurchaseOrders jFrame = new CurrentPurchaseOrders(desktop);
        desktop.add(jFrame);
        MayfairStatic.setMaximum(jFrame);
        jFrame.show();
    }//GEN-LAST:event_btnCurrentPOActionPerformed

    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed
        Products jFrame = new Products(desktop);
        desktop.add(jFrame);
        MayfairStatic.setMaximum(jFrame);
        jFrame.show();
    }//GEN-LAST:event_btnProductsActionPerformed

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        Customers jFrame = new Customers(desktop);
        desktop.add(jFrame);
        MayfairStatic.setMaximum(jFrame);
        jFrame.show();
    }//GEN-LAST:event_btnCustomersActionPerformed

    private void btnPastSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastSOActionPerformed
        PastSalesOrders jFrame = new PastSalesOrders(desktop);
        desktop.add(jFrame);
        MayfairStatic.setMaximum(jFrame);
        jFrame.show();
    }//GEN-LAST:event_btnPastSOActionPerformed

    private void btnPastPOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPastPOActionPerformed
        PastPurchaseOrders jFrame = new PastPurchaseOrders(desktop);
        desktop.add(jFrame);
        MayfairStatic.setMaximum(jFrame);
        jFrame.show();
    }//GEN-LAST:event_btnPastPOActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        Reports jFrame = new Reports(desktop);
        desktop.add(jFrame);
        jFrame.show();
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnRemindersActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnRemindersActionPerformed
    {//GEN-HEADEREND:event_btnRemindersActionPerformed
        Reminders jFrame = new Reminders(desktop);
        desktop.add(jFrame);
        jFrame.show();
    }//GEN-LAST:event_btnRemindersActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCurrentPO;
    private javax.swing.JButton btnCurrentSO;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnNewPO;
    private javax.swing.JButton btnNewSO;
    private javax.swing.JButton btnPastPO;
    private javax.swing.JButton btnPastSO;
    private javax.swing.JButton btnProducts;
    private javax.swing.JButton btnReminders;
    private javax.swing.JButton btnReports;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel panelSelection;
    // End of variables declaration//GEN-END:variables
}
